# Generated by Django 4.0.4 on 2022-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=30, null='false')),
                ('count', models.BigIntegerField(default='0', null='false', unique='true', verbose_name='ID')),
                ('email', models.EmailField(max_length=30, null='TRUE')),
                ('address', models.CharField(max_length=55, null='TRUE')),
                ('phone', models.IntegerField(null='TRUE', verbose_name='phone number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null='TRUE')),
                ('status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null='TRUE', verbose_name='Martial Status')),
                ('vacation', models.IntegerField(null='TRUE', verbose_name='vacation days')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, null='TRUE')),
                ('date', models.DateField(null='TRUE')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null='false', verbose_name='email')),
                ('password', models.TextField(null='false', verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='vac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(null='false')),
                ('end', models.DateField(null='false')),
                ('reason', models.TextField(max_length=500, null='false')),
            ],
        ),
    ]
